export enum TipoBem {
  BEM_PROPRIO = 'BEM_PROPRIO',
  BEM_LOCADO = 'BEM_LOCADO',
  BEM_SERVIDOR = 'BEM_SERVIDOR',
  BEM_COMODATO = 'BEM_COMODATO',
}

export enum EstadoConservacao {
  BOM = 'BOM',
  REGULAR = 'REGULAR',
  RUIM = 'RUIM',
  INSERVIVEL = 'INSERVIVEL',
}

export enum StatusBem {
  ATIVO = 'ATIVO',
  EM_MANUTENCAO = 'EM_MANUTENCAO',
  BAIXADO = 'BAIXADO',
  DEVOLVIDO = 'DEVOLVIDO',
}

export enum StatusManutencao {
  AGUARDANDO_DIAGNOSTICO = 'AGUARDANDO_DIAGNOSTICO',
  AGUARDANDO_CONSERTO = 'AGUARDANDO_CONSERTO',
  EM_CONSERTO = 'EM_CONSERTO',
  CONCLUIDO = 'CONCLUIDO',
}

export enum TipoEtiqueta {
  AVARIA = 'AVARIA',
  SITUACAO_PATRIMONIO = 'SITUACAO_PATRIMONIO',
  BEM_PARTICULAR_SERVIDOR = 'BEM_PARTICULAR_SERVIDOR',
  BEM_LOCADO = 'BEM_LOCADO',
  BEM_COMODATO = 'BEM_COMODATO',
}
